import bcrypt from 'bcryptjs'

const data = {
    users: [
        {
            firstName: "Abhijith",
            lastName: "M",
            email: "abhijith@gmail.com",
            password: bcrypt.hashSync("abhi@123"),
            canSell: true,
        },
        {
            firstName: "Adarsh",
            lastName: "P",
            email: "adarsh@gmail.com",
            password: bcrypt.hashSync("adarsh@123"),
            canSell: true,
        },
        {
            firstName: "Krishna",
            lastName: "Prasad M",
            email: "krishnaprasad@gmail.com",
            password: bcrypt.hashSync("prasad@123"),
            canSell: true,
        },
        {
            firstName: "Thejus",
            lastName: "Prakash",
            email: "thejus@gmail.com",
            password: bcrypt.hashSync("thejus@123"),
            canSell: true,
        }
    ],
    products: [
        {
            name: "Jade Mini Plant",
            slug: "jade-mini-plant",
            price: 199,
            category: "Plants",
            image: "/assets/images/jade_mini_plant.webp",
            countInStock: 15,
            seller: "601c1f1f1f1f1f1f1f1f1f1",
            rating: 4.5,
            numReviews: 34,
            description: "A beautiful jade mini plant to brighten up your space.",
        },
        {
            name: "Peace Lily Plant",
            slug: "peace-lily-plant",
            price: 249,
            category: "Plants",
            image: "/assets/images/peace_lily_plant.webp",
            countInStock: 10,
            seller: "602c2f2f2f2f2f2f2f2f2f2",
            rating: 4.2,
            numReviews: 28,
            description: "A serene peace lily plant that purifies the air.",
        },
        {
            name: "Lucky Bamboo Plant",
            slug: "lucky-bamboo-plant",
            price: 179,
            category: "Plants",
            image: "/assets/images/lucky_bamboo_plant.webp",
            countInStock: 25,
            seller: "604c4f4f4f4f4f4f4f4f4f4",
            rating: 4.7,
            numReviews: 32,
            description: "A lucky bamboo plant that brings good fortune.",
        },
        {
            name: "Money Plant Golden",
            slug: "money-plant-golden",
            price: 299,
            category: "Plants",
            image: "/assets/images/money_plant_golden.webp",
            countInStock: 8,
            seller: "605c5f5f5f5f5f5f5f5f5f5",
            rating: 4.6,
            numReviews: 40,
            description: "A money plant golden variety to attract wealth and prosperity.",
        },
        {
            name: "Monstera Deliciosa Plant",
            slug: "monstera-deliciosa-plant",
            price: 399,
            category: "Plants",
            image: "/assets/images/monstera_deliciosa_plant.webp",
            countInStock: 5,
            seller: "606c6f6f6f6f6f6f6f6f6f6",
            rating: 4.8,
            numReviews: 25,
            description: "A stunning monstera deliciosa plant with large, glossy leaves.",
        },
        {
            name: "Snake Plant - Golden Hahnii",
            slug: "snake-plant-golden-hahnii",
            price: 299,
            category: "Plants",
            image: "/assets/images/snake_plant_golden_hahnii.webp",
            countInStock: 12,
            seller: "607c7f7f7f7f7f7f7f7f7f7",
            rating: 4.4,
            numReviews: 30,
            description: "A beautiful snake plant with golden edges.",
        },
        {
            name: "Bamboo Palm Plant",
            slug: "bamboo-palm-plant",
            price: 249,
            category: "Plants",
            image: "/assets/images/bamboo_palm_plant.webp",
            countInStock: 10,
            seller: "608c8f8f8f8f8f8f8f8f8f8",
            rating: 4.3,
            numReviews: 22,
            description: "A graceful bamboo palm plant that adds elegance to any room.",
        },
        {
            name: "Syngonium Pink Plant",
            slug: "syngonium-pink-plant",
            price: 199,
            category: "Plants",
            image: "/assets/images/syngonium_pink_plant.webp",
            countInStock: 15,
            seller: "609c9f9f9f9f9f9f9f9f9f9",
            rating: 4.5,
            numReviews: 35,
            description: "A vibrant syngonium pink plant with heart-shaped leaves.",
        },
        {
            name: "Cocopeat Block",
            slug: "cocopeat-block",
            price: 99,
            category: "Gardening Supplies",
            image: "/assets/images/cocopeat_block.webp",
            countInStock: 20,
            seller: "60a0a0a0a0a0a0a0a0a0a0a",
            rating: 4.1,
            numReviews: 25,
            description: "A high-quality cocopeat block for your gardening needs.",
        },
        {
            name: "Vermicompost",
            slug: "vermicompost",
            price: 149,
            category: "Gardening Supplies",
            image: "/assets/images/vermicompost.webp",
            countInStock: 15,
            seller: "60b0b0b0b0b0b0b0b0b0b0b",
            rating: 4.3,
            numReviews: 28,
            description: "A nutrient-rich vermicompost for your plants.",
        },
        {
            name: "Garden Soil Mix",
            slug: "garden-soil-mix",
            price: 129,
            category: "Gardening Supplies",
            image: "/assets/images/garden_soil_mix.webp",
            countInStock: 10,
            seller: "60c0c0c0c0c0c0c0c0c0c0c",
            rating: 4.2,
            numReviews: 25,
            description: "A premium garden soil mix for all your gardening needs.",
        },
        {
            name: "Plant Food Fertilizer Green Sticks",
            slug: "plant-food-fertilizer-green-sticks",
            price: 129,
            category: "Gardening Supplies",
            image: "/assets/images/plant_food_fertilizer_green_sticks.webp",
            countInStock: 18,
            seller: "60d0d0d0d0d0d0d0d0d0d0d",
            rating: 4.4,
            numReviews: 30,
            description: "A convenient plant food fertilizer in stick form.",
        },
        {
            name: "SCow Manure",
            slug: "scow-manure",
            price: 159,
            category: "Gardening Supplies",
            image: "/assets/images/scow_manure.webp",
            countInStock: 12,
            seller: "60e0e0e0e0e0e0e0e0e0e0e",
            rating: 4.5,
            numReviews: 28,
            description: "A rich, organic cow manure for your plants.",
        },
        {
            name: "Mealybug Magic Spray",
            slug: "mealybug-magic-spray",
            price: 249,
            category: "Gardening Supplies",
            image: "/assets/images/mealybug_magic_spray.webp",
            countInStock: 20,
            seller: "60f0f0f0f0f0f0f0f0f0f0f",
            rating: 4.6,
            numReviews: 32,
            description: "An effective mealybug magic spray to protect your plants.",
        },
        {
            name: "Neem Guard Ready-to-Use Neem Oil Spray",
            slug: "neem-guard-ready-to-use-neem-oil-spray",
            price: 299,
            category: "Gardening Supplies",
            image: "/assets/images/neem_guard_ready_to_use_neem_oil_spray.webp",
            countInStock: 15,
            seller: "610101010101010101010101",
            rating: 4.7,
            numReviews: 35,
            description: "A ready-to-use neem oil spray for plant protection.",
        },
        {
            name: "Broken Heart Plant",
            slug: "broken-heart-plant",
            price: 199,
            category: "Gardening Supplies",
            image: "/assets/images/broken_heart_plant.webp",
            countInStock: 12,
            seller: "610101010101010101010102",
            rating: 4.5,
            numReviews: 28,
            description: "A beautiful broken heart plant with unique leaf patterns.",
        }
    ]
};
export default data;